project:
  type: book

book:
  title: "Pension Mathematics Reference Guide"
  subtitle: "For Claude Code Integration and Simulation Modeling"
  author: "Don Boyd (with Claude assistance)"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - pension-math-reference.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    code-line-numbers: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-overflow: wrap
    df-print: kable