title: "Pension Mathematics Reference Guide"
subtitle: "For Claude Code Integration and Simulation Modeling"
author: "Don Boyd (with Claude assistance)"
date: today
date-format: long

project:
  type: default

format:
  typst:
    toc: true
    section-numbering: 1.1.a
    columns: 1
    papersize: us-letter
    margin:
      x: 1in
      y: 1in
    output-file: "pension-math-reference"

execute:
  cache: false
  freeze: auto